name: Bidirectional Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - bi-sync

permissions:
  actions: write

jobs:
  partial-sync:
    runs-on: ubuntu-latest
    environment: notion-sync
    env:
      CACHE_KEY: notion-synced-cache
    steps:
      - uses: actions/checkout@v4

      - name: Clear cache
        uses: actions/github-script@v7
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: "${{ env.CACHE_KEY }}",
              })
            }

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup environment
        uses: actions/setup-node@v4.0.3
        with:
          always-auth: false
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Cache Notion Pages
        uses: actions/cache@v4
        with:
          path: .cache
          key: ${{ env.CACHE_KEY }}

      - name: Run Sync
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TOKEN_OF_GITHUB: ${{ secrets.TOKEN_OF_GITHUB }}
          FULLSYNC_LIMIT: 2000
          PARTIALSYNC_LIMIT: 10
          REPO_TOPICS_LIMIT: 50
          BI_SYNC: true
        run: pnpm start
