name: FullSync Notion Star

on:
  workflow_dispatch:

jobs:
  full-sync:
    runs-on: ubuntu-latest
    environment: notion-sync
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - name: Install pnpm

      - name: Setup environment
        uses: actions/setup-node@v4.0.3
        with:
          always-auth: false
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm

      - name: Run Full Sync
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TOKEN_OF_GITHUB: ${{ secrets.TOKEN_OF_GITHUB }}
          FULLSYNC_LIMIT: 2000
          PARTIALSYNC_LIMIT: 10
          REPO_TOPICS_LIMIT: 50
          FULL_SYNC: true
        run: pnpm start
