name: Partial Sync Notion Star

on:
  schedule:
    - cron: '10 8 * * *'
  workflow_dispatch:
jobs:
  partial-sync:
    runs-on: ubuntu-latest
    environment: notion-sync
    steps:
      - uses: actions/checkout@v4

      - name: Download cache storage of last build
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          workflow: partial-sync.yml
          workflow_conclusion: success
          name: notion-sync-storage
          path: .cache

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup environment
        uses: actions/setup-node@v4.0.3
        with:
          always-auth: false
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Restore cached Notion Pages
        uses: actions/cache/restore@v4
        with:
          path: .cache
          keys: notion-sync-storage

      - name: Run Partial Sync
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TOKEN_OF_GITHUB: ${{ secrets.TOKEN_OF_GITHUB }}
          FULLSYNC_LIMIT: 2000
          PARTIALSYNC_LIMIT: 10
          REPO_TOPICS_LIMIT: 50
        run: pnpm start

      - name: Cache Notion Pages
        uses: actions/cache/save@v4
        with:
          path: .cache
          keys: notion-sync-storage
